CREATE USER 'IND_USER' IDENTIFIED BY 'BELLAKO'
DEFAULT TABLESPACE 'DATA'
TEMPORARY TABLESPACE 'TEMP';

-- QUOTAS
ALTER USER 'IND_USER' QUOTA UNLIMITED ON 'DATA';

-- ROLES
GRANT 'CONNECT' TO 'IND_USER' WITH ADMIN OPTION;
GRANT 'RESOURCE' TO 'IND_USER' WITH ADMIN OPTION;

-- SYSTEM PRIVILEGES
GRANT CREATE SEASON TO 'IND_USER' WITH ADMIN OPTION;

-- Creación de tablas para la base de datos del IND

-- Tabla para almacenar información de ubicación
CREATE TABLE Ubicacion (
    ID_Ubicacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Direccion VARCHAR2(200),
    Ciudad VARCHAR2(100),
    Region VARCHAR2(100)
);


-- Tabla para almacenar información de las escuelas deportivas
CREATE TABLE Escuela_Deportiva (
    ID_Escuela NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Tipo_Escuela VARCHAR(50) NOT NULL,
    ID_Ubicacion NUMBER NOT NULL,
    Telefono VARCHAR(20),
    Correo_Electronico VARCHAR(100),
    Sitio_Web VARCHAR(200),
    CONSTRAINT FK_Escuela_Ubicacion FOREIGN KEY (ID_Ubicacion) REFERENCES Ubicacion(ID_Ubicacion)
);

-- Tabla para almacenar información del personal de las escuelas
CREATE TABLE Personal (
    ID_Personal NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_Escuela NUMBER NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Profesion VARCHAR(100),
    Nacionalidad VARCHAR(50),
    Fecha_Nacimiento DATE,
    Telefono VARCHAR(20),
    Correo_Electronico VARCHAR(100),
    CONSTRAINT FK_Personal_Escuela FOREIGN KEY (ID_Escuela) REFERENCES Escuela_Deportiva(ID_Escuela)
);

-- Tabla para almacenar información de los costos asociados a las escuelas
CREATE TABLE Costo (
    ID_Costo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_Escuela NUMBER NOT NULL,
    Fecha DATE NOT NULL,
    Descripcion VARCHAR(200),
    Monto NUMBER NOT NULL,
    Tipo_Costo VARCHAR(50) NOT NULL,
    CONSTRAINT FK_Costo_Escuela FOREIGN KEY (ID_Escuela) REFERENCES Escuela_Deportiva(ID_Escuela)
    );

-- Inserción de datos de ejemplo

-- Datos de ubicación
INSERT INTO Ubicacion (Direccion, Ciudad, Region) VALUES ('Av. Principal 123', 'Santiago', 'Metropolitana');
INSERT INTO Ubicacion (Direccion, Ciudad, Region) VALUES ('Calle Secundaria 456', 'Concepción', 'Biobío');
INSERT INTO Ubicacion (Direccion, Ciudad, Region) VALUES ('Paseo Marítimo 789', 'Valparaíso', 'Valparaíso');
INSERT INTO Ubicacion (Direccion, Ciudad, Region) VALUES ('Camino Real 1011', 'Antofagasta', 'Antofagasta');
    

-- Datos de escuelas deportivas
INSERT INTO Escuela_Deportiva (Nombre, Tipo_Escuela, ID_Ubicacion, Telefono, Correo_Electronico, Sitio_Web) VALUES ('Escuela de Fútbol Los Leones', 'Fútbol', 1, '+56 2 23456789', 'contacto@losleones.cl', 'www.losleones.cl');
INSERT INTO Escuela_Deportiva (Nombre, Tipo_Escuela, ID_Ubicacion, Telefono, Correo_Electronico, Sitio_Web) VALUES ('Club de Baloncesto Las Águilas', 'Baloncesto', 2, '+56 41 2345678', 'info@lasaguilas.cl', NULL);
INSERT INTO Escuela_Deportiva (Nombre, Tipo_Escuela, ID_Ubicacion, Telefono, Correo_Electronico, Sitio_Web) VALUES ('Academia de Natación Delfines', 'Natación', 3, '+56 32 2345678', 'natacion@delfines.cl', 'www.delfines.cl');
INSERT INTO Escuela_Deportiva (Nombre, Tipo_Escuela, ID_Ubicacion, Telefono, Correo_Electronico, Sitio_Web) VALUES ('Escuela de Tenis La Raqueta', 'Tenis', 4, '+56 55 2345678', 'tenis@laraqueta.cl', 'www.laraqueta.cl');


-- Datos de personal
INSERT INTO Personal (ID_Escuela, Nombre, Apellido, Profesion, Nacionalidad, Fecha_Nacimiento, Telefono, Correo_Electronico) VALUES (1, 'Juan', 'Pérez', 'Entrenador', 'Chilena', '1980-05-15', '+56 9 12345678', 'juan.perez@losleones.cl');
INSERT INTO Personal (ID_Escuela, Nombre, Apellido, Profesion, Nacionalidad, Fecha_Nacimiento, Telefono, Correo_Electronico) VALUES (1, 'María', 'González', 'Preparadora Física', 'Argentina', '1985-11-20', '+56 9 98765432', 'maria.gonzalez@losleones.cl');
INSERT INTO Personal (ID_Escuela, Nombre, Apellido, Profesion, Nacionalidad, Fecha_Nacimiento, Telefono, Correo_Electronico) VALUES (2, 'Pedro', 'Rodríguez', 'Entrenador', 'Chilena', '1975-03-10', '+56 9 45678901', 'pedro.rodriguez@lasaguilas.cl');
INSERT INTO Personal (ID_Escuela, Nombre, Apellido, Profesion, Nacionalidad, Fecha_Nacimiento, Telefono, Correo_Electronico) VALUES (3, 'Ana', 'Martínez', 'Entrenadora', 'Chilena', '1990-09-30', '+56 9 23456789', 'ana.martinez@delfines.cl');

-- Datos de costos
INSERT INTO Costo (ID_Escuela, Fecha, Descripcion, Monto, Tipo_Costo) VALUES (1, '2023-08-15', 'Pago entrenador Juan Pérez', 500000, 'Pago Entrenador');
INSERT INTO Costo (ID_Escuela, Fecha, Descripcion, Monto, Tipo_Costo) VALUES (1, '2023-09-01', 'Compra de balones de fútbol', 150000, 'Compra Equipo');
INSERT INTO Costo (ID_Escuela, Fecha, Descripcion, Monto, Tipo_Costo) VALUES (2, '2023-07-20', 'Pago entrenador Pedro Rodríguez', 450000, 'Pago Entrenador');
INSERT INTO Costo (ID_Escuela, Fecha, Descripcion, Monto, Tipo_Costo) VALUES (3, '2023-06-10', 'Compra de insumos de limpieza', 80000, 'Insumos');


-- Consultas de ejemplo

-- Mostrar todas las escuelas deportivas con su información de ubicación
SELECT ed.Nombre, ed.Tipo_Escuela, u.Direccion, u.Ciudad, u.Region 
FROM Escuela_Deportiva ed
JOIN Ubicacion u ON ed.ID_Ubicacion = u.ID_Ubicacion;

-- Mostrar las escuelas deportivas ubicadas en la Región Metropolitana
SELECT ed.Nombre, ed.Tipo_Escuela, u.Direccion, u.Ciudad, u.Region 
FROM Escuela_Deportiva ed
JOIN Ubicacion u ON ed.ID_Ubicacion = u.ID_Ubicacion
WHERE u.Region = 'Metropolitana';

-- Mostrar el personal de la escuela con ID_Escuela = 1
SELECT * FROM Personal WHERE ID_Escuela = 1;

